# Configuration to test versioning support in development

# To use run `hugo -e versioning` or `hugo server -e versioning` from the `docs` directory

# It uses the docs as the current version and abuses the exampleSite
# as an archived version

baseURL = 'http://localhost:1313/'
[params]
  version = 'latest'
  versions = [
    { identifier = 'latest', title = '1.0', baseURL = 'http://localhost:1313/', isLatest = true},
    { identifier = '0.666', title = '0.666', baseURL = 'http://localhost:1414/exampleSite/'},
  ]
