# showcase of the menu shortcuts;
# you can use relative URLs linking to your content or use
# fully-qualified URLs to link outside of your project

[en]
  title = 'Purple Pulpo'
  weight = 1
  languageCode = 'en'
  languageName = 'English'
  # Language dependent settings:
  # Use case https://gohugo.io/content-management/multilingual/#translation-by-content-directory
  contentDir = 'content/en'
  [en.params]
    landingPageName = '<i class="fa-fw fas fa-anchor"></i> Home'

[[en.menu.shortcuts]]
  pre = '<i class="fa-fw fas fa-puzzle-piece"></i> '
  name = 'Relearn Docs'
  url = 'https://mcshelby.github.io/hugo-theme-relearn/index.html'
  weight = 10
[[en.menu.shortcuts]]
  pre = '<i class="fa-fw fab fa-github"></i> '
  name = 'GitHub Repo'
  url = 'https://github.com/McShelby/hugo-theme-relearn'
  weight = 20

# this is ourrr way t' showcase th' multilang settings by
# doing autotrrranlat'n of th' english content; we are
# lazy and don't supporrt furrrther trrranslations; arrr,
# don't take it t' serrrious, fello'; it's prrretty hacky and:
# NOT MEANT FER PRRRODUCTION! ARRR!

[pir]
  title = "Purple Pulpo"
  weight = 2
  # It would be more standard compliant to have the language key also
  # named art-x-pir but that would require to rename all files
  languageCode = 'art-x-pir'
  languageDirection = 'rtl' # you can explicitly override the reading direction here, otherwise the translation file contains a default
  languageName = 'Arrr! ☠ Pirrratish ☠'
  # Language dependent settings:
  # Use case https://gohugo.io/content-management/multilingual/#translation-by-content-directory
  contentDir = 'content/pir'
  [pir.params]
    landingPageName = '<i class="fa-fw fas fa-anchor"></i> Arrr! Home'
    urlIgnoreCheck = ['.*']

[[pir.menu.shortcuts]]
  pre = '<i class="fa-fw fas fa-puzzle-piece"></i> '
  name = 'Relearn Docs'
  url = 'https://mcshelby.github.io/hugo-theme-relearn/pir/index.html'
  weight = 10
[[pir.menu.shortcuts]]
  pre = '<i class="fa-fw fab fa-github"></i> '
  name = 'GitHub Repo'
  url = 'https://github.com/McShelby/hugo-theme-relearn'
  weight = 20
