baseURL = "https://gokrazy.org/"
languageCode = "en-us"
title = "gokrazy"
theme = "hugo-theme-relearn"
disableKinds = ["RSS", "taxonomyTerm"]
publishDir = "../docs/"
enableRobotsTXT = true

[markup.goldmark.renderer]
# Required for e.g. <img> tags in markdown articles.
unsafe = true

[params]
  disableInlineCopyToClipBoard = true
  disableNextPrev = true
  editURL = "https://github.com/gokrazy/gokrazy/tree/master/website/content/"

# TODO(later): change color to grey for logo?

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/gokrazy/gokrazy"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON"]

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
